-- MySQL Script generated by MySQL Workbench
-- Sun Aug 13 11:51:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema meetingtecnologydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `meetingtecnologydb` ;

-- -----------------------------------------------------
-- Schema meetingtecnologydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meetingtecnologydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `meetingtecnologydb` ;

-- -----------------------------------------------------
-- Table `meetingtecnologydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetingtecnologydb`.`usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `meetingtecnologydb`.`usuarios` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `meetingtecnologydb`.`usuarios` (`email` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `meetingtecnologydb`.`canal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetingtecnologydb`.`canal` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `meetingtecnologydb`.`canal` (
  `idcanal` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idcanal_UNIQUE` ON `meetingtecnologydb`.`canal` (`idcanal` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `meetingtecnologydb`.`usuarios_has_canal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetingtecnologydb`.`usuarios_has_canal` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `meetingtecnologydb`.`usuarios_has_canal` (
  `usuarios_idUser` INT NOT NULL,
  `canal_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuarios_idUser`, `canal_usuario`),
  CONSTRAINT `fk_usuarios_has_canal_usuarios`
    FOREIGN KEY (`usuarios_idUser`)
    REFERENCES `meetingtecnologydb`.`usuarios` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_canal_canal1`
    FOREIGN KEY (`canal_usuario`)
    REFERENCES `meetingtecnologydb`.`canal` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_usuarios_has_canal_canal1_idx` ON `meetingtecnologydb`.`usuarios_has_canal` (`canal_usuario` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_usuarios_has_canal_usuarios_idx` ON `meetingtecnologydb`.`usuarios_has_canal` (`usuarios_idUser` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
